<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose an optionBeigeBlack</name>
   <tag></tag>
   <elementGuidId>ec93d145-efda-4420-abe0-95841589dea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pa_color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pa_color']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d816d8cc-f082-4110-8434-41e342d0d8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pa_color</value>
      <webElementGuid>9a3a93f1-bfe2-4536-abaf-f10edeb607c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_pa_color</value>
      <webElementGuid>3bdf4404-25a9-4bf6-89e9-d46742280cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_pa_color</value>
      <webElementGuid>751574a3-2b2e-43c8-b160-8487fe902cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>cefc1645-44f3-4fb2-9af2-076a4f593c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose an optionBeigeBlack</value>
      <webElementGuid>8a575145-37bb-4eec-93ed-d3d8e05595c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pa_color&quot;)</value>
      <webElementGuid>82b51856-50d5-42ef-b3b7-1f3333dbc211</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pa_color']</value>
      <webElementGuid>021d348f-6a3d-4605-8a62-549ffc68f147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-1162']/div/div[2]/form/table/tbody/tr/td/select</value>
      <webElementGuid>197d843e-df42-434c-a64a-b4194d3c709f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/following::select[1]</value>
      <webElementGuid>e03275a5-8277-49b0-a8a8-5364eb4f859b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹'])[3]/following::select[1]</value>
      <webElementGuid>ee58b389-9d5f-40d5-b73b-68451855ebbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/preceding::select[1]</value>
      <webElementGuid>7933acfc-e911-4b94-8343-261206c26939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QTY'])[1]/preceding::select[2]</value>
      <webElementGuid>7176eb58-a2c1-4b92-b134-6bdbcaa88375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>884be09c-9fa6-43a7-bb3e-681c5b1c7801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pa_color' and @name = 'attribute_pa_color' and (text() = 'Choose an optionBeigeBlack' or . = 'Choose an optionBeigeBlack')]</value>
      <webElementGuid>3cfe587d-4e72-479d-8b32-f59af1d5d2b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
