<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billing_phone</name>
   <tag></tag>
   <elementGuidId>e16b38fe-09eb-4df6-a0d6-010a0f8fc697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c9c8234-73bb-45a8-b74f-27e2fbcbb9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>3cee365b-7ea2-40e3-8d7c-99f3ce2cccf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>5a52f3f3-0428-4a92-bf10-6807ed91241b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_phone</value>
      <webElementGuid>f7602d62-4f26-41cd-a08d-50dd5c466e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_phone</value>
      <webElementGuid>112ac09f-09fe-4b1f-a07f-9d06d9f9a8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>efdd8767-9d8f-4268-964b-cb51788a1c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_phone&quot;)</value>
      <webElementGuid>262d0a4d-860f-4c4a-a2bc-6f7b6048d730</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_phone']</value>
      <webElementGuid>955f8109-58f1-4b7b-b996-dd9a959fb7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_phone_field']/span/input</value>
      <webElementGuid>5dd8803b-2c4b-40ec-a0dd-f2387c24c916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/span/input</value>
      <webElementGuid>e2d8b6ab-f185-45b6-9c6a-275c768f48c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'billing_phone' and @id = 'billing_phone']</value>
      <webElementGuid>22e889df-1048-4082-bd4e-23513d53b954</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
