<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Delhi</name>
   <tag></tag>
   <elementGuidId>10c9e291-027f-490d-8f32-a5e4157055fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-billing_state-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-billing_state-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b5cd8d56-5599-43e1-a2b4-0f1600219fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>f9c1b6dc-c2df-4932-875e-641b850ef835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-billing_state-container</value>
      <webElementGuid>ad616239-72eb-4d3e-85c1-a046158642f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>218db9b7-251b-4e86-9f08-b4400bfa6162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>553549a7-df6a-4ddc-a28f-bd6f6f06afe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delhi</value>
      <webElementGuid>684de7cd-9741-40e2-a6d9-28250aa13c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delhi</value>
      <webElementGuid>93f3f5de-ff3f-4403-8a3b-9a04284e8173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-billing_state-container&quot;)</value>
      <webElementGuid>9278f1fa-86b1-42db-b1aa-aa53d7f84f43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-billing_state-container']</value>
      <webElementGuid>f0c33a1f-debe-4c78-8e08-925ad0a0eb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_state_field']/span/span/span/span/span</value>
      <webElementGuid>25ae67c1-500b-4ddd-a072-1d9c8235ee63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::span[5]</value>
      <webElementGuid>d77c908d-a075-4472-b690-ed93df77205b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/preceding::span[3]</value>
      <webElementGuid>8bfe2230-e976-4c79-8beb-695733579e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[8]/span/span/span/span/span</value>
      <webElementGuid>4dd69454-326a-4223-9182-8109a7de609a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-billing_state-container' and @title = 'Delhi' and (text() = 'Delhi' or . = 'Delhi')]</value>
      <webElementGuid>6f9c7fe6-6bfb-4c1f-832e-9a9c43030a7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
